INSERT INTO `criteria` (`criteria_id`, `category_id`, `text`) VALUES
(12, 11, 'noudattaa sosiaali- ja terveysalan säädöksiä, säännöksiä, määräyksiä ja eettisiä periaatteita muuttuvissa tilanteissa.\r\n'),
(13, 11, 'toimii kestävän kehityksen periaatteiden mukaisesti ja perustelee toimintaansa.\r\n'),

(14, 12, 'asettaa tavoitteita työlleen yhdessä asiakkaiden kanssa tarve- ja kulttuurilähtöisesti ja suunnittelee työtään sen pohjalta.\r\n'),
(15, 12, 'esittää vaihtoehtoisia toimintatapoja ja tekee työtä asiakaslähtöisesti perustellen toimintaansa.\r\n'),
(16, 12, 'suunnittelee päivittäiset ja viikoittaiset työtehtävänsä ja ottaa huomioon työpaikan muut toiminnan suunnitelmat.\r\n'),
(17, 12, 'toimii moniammatillisen työryhmän jäsenenä lähihoitajan vastuualueella.\r\n'),
(18, 12, 'osallistuu asiakkaalle tehtävän terveyttä ja hyvinvointia edistävän suunnitelman laatimiseen yhdessä asiakkaan ja läheistensä kanssa.\r\n'),
(19, 12, 'toteuttaa suunnitelmaa yhdessä työryhmän kanssa.\r\n'),
(20, 12, 'perehtyy työpaikan eri omavalvontasuunnitelmiin ja toteuttaa yksikön omavalvontaa osana työryhmää.\r\n'),
(21, 12, 'työskentelee omavalvontamääräysten mukaisesti.\r\n'),

(22, 13, 'toimii ammatillisesti vuorovaikutustilanteissa osana työryhmää.\r\n'),
(23, 13, 'huomioi oman käyttäytymisensä vaikutukset vuorovaikutustilanteissa.\r\n'),
(24, 13, 'ohjaa asiakasta toistuvissa päivittäisissä tilanteissa hyödyntäen selkokieltä ja puhetta tukevia ja korvaavia kommunikointikeinoja.\r\n'),
(25, 13, 'kohtaa asiakkaan ja tämän lähiverkoston työryhmän jäsenenä.\r\n'),
(26, 13, 'huomioi asiakkaan eleet ja ilmeet.\r\n'),
(27, 13, 'käyttää kosketusta vuorovaikutuksen tukena.\r\n'),

(28, 14, 'arvioi asiakkaan voimavarat hyödyntäen havainnointia sekä asiakkaan ja omaisten haastattelua.\r\n'),
(29, 14, 'käyttää suunnitelmallisesti, tavoitteellisesti ja joustavasti asiakkaan toimintakykyä edistävää voimavaralähtöistä työotetta.\r\n'),
(30, 14, 'kuulee asiakkaan mielipiteitä ja toiveita tukien monipuolisesti asiakkaan osallisuutta ja elämän merkityksellisyyttä.\r\n'),
(31, 14, 'huomioi asiakkaan läheiset ja sosiaalisen hyvinvoinnin verkostot.\r\n'),

(32, 15, 'motivoi itsenäisesti asiakasta terveyttä ja hyvinvointia edistävään omahoitoon sekä elämäntapamuutoksiin.\r\n'),
(33, 15, 'edistää monipuolisesti erilaisten ja eri-ikäisten asiakkaiden fyysistä ja psyykkistä terveyttä sekä turvallisuutta ja hyvinvointia muuttuvissa tilanteissa.\r\n'),
(34, 15, 'tunnistaa perhe- ja lähisuhdeväkivallan uhkan ja kaltoinkohtelun ja ottaa sen puheeksi työryhmässä.\r\n'),
(35, 15, 'tunnistaa, ehkäisee ja ohjaa asiakasta välttämään kansanterveydellisiä riskejä ja tapaturmia.\r\n'),
(36, 15, 'tarjoaa asiakkaalle mahdollisuuksia selviytyä päivittäisissä toiminnoissa hyödyntäen asiakkaan omaa verkostoa ja ympäristön tarjoamia mahdollisuuksia.\r\n'),

(37, 16, 'ohjaa ja kannustaa asiakasta toiminnallisuuteen päivittäisissä toiminnoissa.\r\n'),
(38, 16, 'mahdollistaa asiakkaalle soveltuvan liikunnan ja ulkoilun.\r\n'),
(39, 16, 'tarjoaa asiakkaalle toimintaa käyttäen eri toiminnallisia menetelmiä.\r\n'),
(40, 16, 'huomioi asiakkaan mielenkiinnon kohteet ohjatessaan asiakasta sosiaaliseen toimintaan sekä tarjoaa uusia osallistumisen mahdollisuuksia.\r\n'),

(41, 17, 'tukee, ohjaa ja motivoi asiakkaita selviytymään päivittäisissä toiminnoissa voimavaralähtöisesti toistuvissa työtilanteissa.\r\n'),
(42, 17, 'havaitsee joitakin asiakkaan sosiaalisen tuen tarpeita tai ongelmia ja tiedottaa havainnoistaan työryhmälle.\r\n'),
(43, 17, 'huomioi asiakkaan seksuaali- ja lisääntymisterveyden.\r\n'),
(44, 17, 'huomioi asiakkaan seksuaalisen suuntautumisen moninaisuuden osana työryhmää.\r\n'),
(45, 17, 'huomioi asiakkaan kulttuurin osana työryhmää.\r\n'),
(46, 17, 'huomioi asiakkaan unen ja levon tarpeen.\r\n'),
(47, 17, 'hyödyntää työssään tietoa saattohoidosta ja kuolevan potilaan hoidosta.\r\n'),
(48, 17, 'huomioi asiakkaan ja omaiset saattohoidossa.\r\n'),
-- täytyy kysyä että miks osaan.fi antaa kaks kertaa samalla tehtävänimellä, onko siihen joku esim lakisääteinen syy 
(49, 17, 'osallistuu työryhmän jäsenenä saattohoitoon ja kuolevan potilaan hoitoon.\r\n'),
(50, 17, 'toteuttaa mielenterveys- ja päihdesairauksia sairastavien hoitoa ja edistää toimintakykyisyyttä työryhmän ohjeiden mukaan.\r\n'),
(51, 17, 'toteuttaa kivunhoitoa käyttäen erilaisia kivunlievitysmenetelmiä työryhmän jäsenenä.\r\n'),
(52, 17, 'toimii oman vastuualueensa mukaisesti sekä turvallisesti yksikön ja asiakkaan lääkehoitosuunnitelmaa noudattaen.\r\n'),
(53, 17, 'tietää yleisimpien lääketietokantojen toimintaperiaatteet ja hyödyntää niitä työssään.\r\n'),
(54, 17, 'käsittelee ja annostelee lääkkeet aseptisesti, virheettömästi ja turvallisesti.\r\n'),
(55, 17, 'tekee virheettömästi annoslaskut sekä yksikönmuunnokset.\r\n'),
(56, 17, 'tunnistaa asiakkaan lääkehoidon tarpeen ja muutostarpeen, tarkistaa asiakkaan lääkityslistan ajantasaisuuden ja selvittää mahdolliset riskitiedot kuten lääkeaineallergiat.\r\n'),
(57, 17, 'antaa lääkkeet luonnollista tietä, injektiona ihon alle ja lihakseen ja hengitettynä ohjeiden mukaan.\r\n'),
(58, 17, 'tietää ja tarkkailee tavallisimpien muisti-, pitkäaikais- ja kansansairauksissa sekä mielenterveys- ja päihdesairauksissa käytettävien lääkkeiden vaikutuksia, yhteisvaikutuksia ja monilääkityksiä, tunnistaa yleisimpiä haitta- ja sivuvaikutuksia sekä huomioi mahdollisia lääkkeiden väärinkäytön ilmiöitä ja tiedottaa niistä työryhmässä.\r\n'),
(59, 17, 'ohjaa asiakasta ja hänen lähiverkostoaan työyksikön ohjeiden mukaisesti sähköisen lääkemääräyksen tulkinnassa ja voimassaoloajassa, lääkkeiden käytössä, säilyttämisessä ja hävittämisessä sekä hallitsee tavallisimpien muisti-, pitkäaikais- ja kansansairauksien sekä mielenterveys- ja päihdesairauksien lääkehoidon.\r\n'),
(60, 17, 'tietää työyksikön lääkityspoikkeamien raportointimenetelmän ja toimii ohjeiden mukaisesti sekä ilmoittaa lääkityspoikkeamasta.\r\n'),
(61, 17, 'osallistuu työryhmän jäsenenä saattohoitoon ja kuolevan potilaan hoitoon.\r\n'),
(62, 17, 'arvioi ja huomioi kokonaisvaltaisesti asiakkaan ravitsemuksen tarpeen ja suun terveyden sekä varmistaa ruoan saannin moniammatillisena yhteistyönä.\r\n'),
(63, 17, 'motivoi ja ohjaa monipuolisesti asiakasta ravitsemuksessa huomioiden ravitsemussuositukset ja erityisruokavaliot, uskonnolliset ja eettiset ruokavaliot sekä suun terveyden.\r\n'),
(64, 17, 'toteuttaa asiakkaan ravitsemushoitoa.\r\n'),
(65, 17, 'huomioi monipuolisesti esteettisyyden ravitsemuksessa.\r\n'),
(66, 17, 'ohjaa aktiivisesti asiakasta ja hänen lähiverkostoaan työyksikön ohjeiden mukaisesti sähköisen lääkemääräyksen tulkinnassa, voimassaoloajassa, lääkkeiden käytössä, säilyttämisessä ja hävittämisessä sekä hallitsee tavallisimpien muisti-, pitkäaikais- ja kansansairauksien sekä mielenterveys- ja päihdesairauksien lääkehoidon.\r\n'),
(67, 17, 'tietää työyksikön lääkityspoikkeamien raportointimenetelmän ja toimii ohjeiden mukaisesti ja ilmoittaa lääkityspoikkeamasta.\r\n'),
(68, 17, 'arvioi ja huomioi kokonaisvaltaisesti asiakkaan ravitsemuksen tarpeen ja suun terveyden sekä varmistaa ruoan saannin moniammatillisena yhteistyönä.\r\n'),
(69, 17, 'motivoi ja ohjaa monipuolisesti asiakasta ravitsemuksessa huomioiden ravitsemussuositukset ja erityisruokavaliot, uskonnolliset ja eettiset ruokavaliot sekä suun terveyden.\r\n'),
(70, 17, 'toteuttaa asiakkaan ravitsemushoitoa.\r\n'),
(71, 17, 'huomioi monipuolisesti esteettisyyden ravitsemuksessa.\r\n'),
(72, 17, 'toteuttaa asiakkaan ravitsemushoitoa.\r\n'),
(73, 17, 'huomioi monipuolisesti esteettisyyden ravitsemuksessa.\r\n'),
(74, 17, 'huomioi monipuolisesti esteettisyyden ravitsemuksessa.\r\n'),

(75, 18, 'tuntee palveluohjauksen prosessin ja antaa asiakkaalle ja lähiverkostolle monipuolista tietoa sosiaali- ja terveysalan palveluista ja etuuksista.\r\n'),
(76, 18, 'ohjaa asiakasta tarvittavien palveluiden piiriin huomioiden asiakkaan ja lähiverkoston tarpeet ja perustelee toimintaansa.\r\n'),
(77, 18, 'tuo esille erilaisia asiakasta vahvistavia palveluita ja tarjoaa vaihtoehtoja asiakkaalle ja tämän lähiverkostolle.\r\n'),
(78, 18, 'tukee asiakasta ja hänen lähiverkostoaan päätöksenteossa.\r\n'),

(79, 19, 'ohjaa monipuolisesti hyvinvointia ja toimintakykyä tukevan teknologian käytössä.\r\n'),
(80, 19, 'kartoittaa asiakkaan apuvälinetarpeen ja hyödyntää apuvälineiden ja hyvinvointiteknologian jakelukanavia.\r\n'),
(81, 19, 'ohjaa monipuolisesti apuvälineiden käytössä ja huollossa ja ehkäisee toiminnallaan laitteisiin liittyvien vaaratilanteiden syntymistä.\r\n'),
(82, 19, 'ohjaa ja käyttää asiakkaan liikkumisen ja siirtymisen apuvälineitä turvallisesti.\r\n'),

(83, 20, 'noudattaa työhyvinvointi- ja työturvallisuusohjeita sekä -määräyksiä.\r\n'),
(84, 20, 'tuntee työpaikan turvallisuussuunnitelman.\r\n'),
(85, 20, 'tuntee vaaratilanteiden ilmoittamisen käytännöt ja toimii osana työryhmää tilanteen edellyttämällä tavalla.\r\n'),
(86, 20, 'ylläpitää työkykyään ja työssä jaksamistaan.\r\n'),
(87, 20, 'hyödyntää terveysliikuntaa sekä ehkäisee työtapaturmia.\r\n'),
(88, 20, 'työskentelee turvallisesti soveltaen työryhmän jäsenenä ergonomian ja työturvallisuuden periaatteita ja ehkäisten työstä aiheutuvia tapaturmia ja haittoja.\r\n'),
(89, 20, 'arvioi ja huomioi työskentelyssään hoitotyön fyysiset ja psyykkiset kuormitustekijät.\r\n'),
(90, 20, 'ymmärtää ergonomian ja asiakkaan toimintakyvyn ylläpitämisen merkityksen tuki- ja liikuntaelinongelmien ennaltaehkäisyssä ja hoidon laadussa.\r\n'),
(91, 20, 'arvioi asiakkaan toimintakyvyn ja valitsee hänen toimintakykyään tukevan auttamistavan ja apuvälineen.\r\n'),
(92, 20, 'huomioi potilasasiakirjojen käsittelyyn liittyvän tietoturvan ja toimii salassapito-ohjeiden mukaan.\r\n'),
(93, 20, 'toimii aseptisen työskentelyn periaatteiden mukaan.\r\n'),
(94, 20, 'huomioi tartuntatautien torjuntatyön säädökset ja estää toiminnallaan tartuntojen leviämisen.\r\n'),
(95, 20, 'käyttää turvallisesti ja sujuvasti apuvälineitä avustustilanteissa.\r\n'),
(96, 20, 'kohtaa haasteellisesti käyttäytyvän asiakkaan ja huomioi työpaikan turvallisuuskäytännöt.\r\n'),

(97, 21, 'arvioi omaa toimintaansa ja ammatillista kehittymistään sekä antaa palautetta ja hyödyntää saamaansa palautetta monipuolisesti.\r\n'),
(98, 21, 'ylläpitää ja kehittää ammatin edellyttämiä tietoja ja taitoja.\r\n'),
(99, 21, 'perustelee monipuolisesti työhönsä liittyviä ratkaisuja näyttöön perustuvalla tiedolla ja hakee tietoa luotettavista lähteistä.\r\n'),
(100, 21, 'tekee itsenäisiä päätöksiä lähihoitajan vastuualueella yhteistyössä asiakkaan sekä tämän läheisten ja verkoston kanssa.\r\n'),
(101, 21, 'tekee realistisia kehittämisehdotuksia asiakkaan terveyden ja hyvinvoinnin lisäämiseksi ja toimii aktiivisesti hyvinvointia edistäen.\r\n');